<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>hu.qgears</groupId>
		<artifactId>hu.qgears.gendoc.parent</artifactId>
		<version>7.0.0-SNAPSHOT</version>
		<relativePath>../../build/hu.qgears.gendoc.parent</relativePath>
	</parent>
	<artifactId>hu.bme.mit.documentation.ecore</artifactId>
	<packaging>jar</packaging>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.eclipse.xtend</groupId>
				<artifactId>xtend-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.tautua.markdownpapers</groupId>
			<artifactId>markdownpapers-core</artifactId>
		</dependency>
		<dependency>
			<groupId>hu.qgears</groupId>
			<artifactId>hu.qgears.commons</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.xtext</groupId>
			<artifactId>org.eclipse.xtext.xbase.lib</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.xtend</groupId>
			<artifactId>org.eclipse.xtend.lib</artifactId>
		</dependency>

		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.ecore</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.ecore.xcore.lib</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.mwe.utils</artifactId>
		</dependency>
		<dependency>
		    <groupId>hu.qgears</groupId>
		    <artifactId>hu.qgears.documentation</artifactId>
		</dependency>
	</dependencies>
</project>